version: '3.9'

services:
  gestbusiness:
    build: ./GestBusiness
    ports:
      - "3000:3000"
    env_file:
      - ./GestBusiness/.env
    restart: always

  gestusers:
    build: ./GestUsers
    ports:
      - "5000:5000"
    env_file:
      - ./GestUsers/.env
    restart: always
